services:
  php:
    container_name: aurora-php
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - aurora_network

  nginx:
    container_name: aurora-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - aurora_network

  postgres:
    container_name: aurora-postgres
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    tty: true
    volumes:
      - aurora_psql_data:/var/lib/postgresql/data:rw
    networks:
      - aurora_network
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-aurora_psql}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-aurora}

  mongo:
    container_name: aurora-mongo
    image: mongo:7.0
    tty: true
    restart: unless-stopped
    networks:
      - aurora_network
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-aurora_nosql}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
      MONGODB_DB: ${MONGODB_DB:-aurora_nosql}
      MONGODB_USER: ${MONGODB_USER:-aurora}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD:-password}
    volumes:
      - ./docker/mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

  cypress:
    container_name: aurora-cypress
    image: cypress/included:13.10.0
    environment:
      - CYPRESS_BASE_URL=http://nginx
      - :80
    depends_on:
      - nginx
      - php
    entrypoint: [ '/bin/sh', '-c' ]
    command: ['npm install && cypress run']
    volumes:
      - .:/cy
    working_dir: /cy
    networks:
      - aurora_network

networks:
  aurora_network:
    driver: bridge

volumes:
  aurora_psql_data:
