create:
  path: /
  controller: App\Controller\Api\AgentApiController::create
  methods: ['POST']

get:
  path: /{id}
  controller: App\Controller\Api\AgentApiController::get
  methods: ['GET']

list:
  path: /
  controller: App\Controller\Api\AgentApiController::list
  methods: ['GET']

remove:
  path: /{id}
  controller: App\Controller\Api\AgentApiController::remove
  methods: ['DELETE']

update:
  path: /{id}
  controller: App\Controller\Api\AgentApiController::update
  methods: ['PATCH']
