get:
  path: /{id}
  controller: App\Controller\Api\EventApiController::get
  methods: ['GET']

list:
  path: /
  controller: App\Controller\Api\EventApiController::list
  methods: ['GET']

remove:
  path: /{id}
  controller: App\Controller\Api\EventApiController::remove
  methods: ['DELETE']
