get:
  path: /{id}
  controller: App\Controller\Api\InitiativeApiController::get
  methods: ['GET']

list:
  path: /
  controller: App\Controller\Api\InitiativeApiController::list
  methods: ['GET']

remove:
  path: /{id}
  controller: App\Controller\Api\InitiativeApiController::remove
  methods: ['DELETE']

create:
  path: /
  controller: App\Controller\Api\InitiativeApiController::create
  methods: ['POST']
