create:
  path: /
  controller: App\Controller\Api\OpportunityApiController::create
  methods: ['POST']

get:
  path: /{id}
  controller: App\Controller\Api\OpportunityApiController::get
  methods: ['GET']

list:
  path: /
  controller: App\Controller\Api\OpportunityApiController::list
  methods: ['GET']

remove:
  path: /{id}
  controller: App\Controller\Api\OpportunityApiController::remove
  methods: ['DELETE']
