get:
  path: /{id}
  controller: App\Controller\Api\OpportunityApiController::get
  methods: ['GET']

list:
  path: /
  controller: App\Controller\Api\OpportunityApiController::list
  methods: ['GET']
