get:
  path: /{id}
  controller: App\Controller\Api\OrganizationApiController::get
  methods: ['GET']

list:
  path: /
  controller: App\Controller\Api\OrganizationApiController::list
  methods: ['GET']

remove:
  path: /{id}
  controller: App\Controller\Api\OrganizationApiController::remove
  methods: ['DELETE']
