create:
  path: /
  controller: App\Controller\Api\SealApiController::create
  methods: ['POST']

get:
  path: /{id}
  controller: App\Controller\Api\SealApiController::get
  methods: ['GET']

list:
  path: /
  controller: App\Controller\Api\SealApiController::list
  methods: ['GET']

remove:
  path: /{id}
  controller: App\Controller\Api\SealApiController::remove
  methods: ['DELETE']

update:
  path: /{id}
  controller: App\Controller\Api\SealApiController::update
  methods: ['PATCH']
