create:
  path: /
  controller: App\Controller\Api\SpaceApiController::create
  methods: ['POST']

get:
  path: /{id}
  controller: App\Controller\Api\SpaceApiController::get
  methods: ['GET']

list:
  path: /
  controller: App\Controller\Api\SpaceApiController::list
  methods: ['GET']

remove:
  path: /{id}
  controller: App\Controller\Api\SpaceApiController::remove
  methods: ['DELETE']
