create:
  path: /
  controller: App\Controller\Api\UserApiController::create
  methods: ["POST"]

update:
  path: /{id}
  controller: App\Controller\Api\UserApiController::update
  methods: ["PATCH"]
