list:
  path: /iniciativas
  controller: App\Controller\Web\InitiativeWebController::list
  methods: ['GET']

show:
  path: /iniciativas/{id}
  controller: App\Controller\Web\InitiativeWebController::show
  methods: ['GET']
