add:
  path: /adicionar
  controller: App\Controller\Web\Admin\DashboardAdminController::index
  methods: ['GET', 'POST']

list:
  path: /
  controller: App\Controller\Web\Admin\DashboardAdminController::index
  methods: ['GET']

remove:
  path: /{id}/remover
  controller: App\Controller\Web\Admin\DashboardAdminController::index
  methods: ['GET']

edit:
  path: /{id}/editar
  controller: App\Controller\Web\Admin\DashboardAdminController::index
  methods: ['GET', 'POST']
