list:
  path: /
  controller: App\Controller\Web\Admin\AgentAdminController::list
  methods: ['GET']

create:
  path: /adicionar
  controller: App\Controller\Web\Admin\AgentAdminController::create
  methods: ['GET', 'POST']

remove:
  path: /{id}/remove
  controller: App\Controller\Web\Admin\AgentAdminController::remove
  methods: ['GET']

timeline:
  path: /{id}/timeline
  controller: App\Controller\Web\Admin\AgentAdminController::timeline
  methods: ['GET']
