add:
  path: /adicionar
  controller: App\Controller\Web\Admin\OrganizationAdminController::add
  methods: ['GET', 'POST']

list:
  path: /
  controller: App\Controller\Web\Admin\OrganizationAdminController::list
  methods: ['GET']

remove:
  path: /{id}/remove
  controller: App\Controller\Web\Admin\OrganizationAdminController::remove
  methods: ['GET']

timeline:
  path: /{id}/timeline
  controller: App\Controller\Web\Admin\OrganizationAdminController::timeline
  methods: ['GET']
