list:
  path: /
  controller: App\Controller\Web\Admin\OrganizationAdminController::list
  methods: ['GET']

remove:
  path: /{id}/remove
  controller: App\Controller\Web\Admin\OrganizationAdminController::remove
  methods: ['GET']
