list:
  path: /
  controller: App\Controller\Web\Admin\RegistrationAdminController::list
  methods: ['GET']

get:
  path: /{id}
  controller: App\Controller\Web\Admin\RegistrationAdminController::get
  methods: ['GET']
