add:
  path: /adicionar
  controller: App\Controller\Web\Admin\SealAdminController::add
  methods: ['GET', 'POST']

list:
  path: /
  controller: App\Controller\Web\Admin\SealAdminController::list
  methods: ['GET']

getOne:
  path: /{id}
  controller: App\Controller\Web\Admin\SealAdminController::getOne
  methods: ['GET']

remove:
  path: /{id}/remove
  controller: App\Controller\Web\Admin\SealAdminController::remove
  methods: ['GET']
