list:
  path: /
  controller: App\Controller\Web\Admin\SealAdminController::list
  methods: ['GET']

getOne:
  path: /{id}
  controller: App\Controller\Web\Admin\SealAdminController::getOne
  methods: ['GET']
