list:
  path: /
  controller: App\Controller\Web\Admin\SpaceAdminController::list
  methods: ['GET']

remove:
  path: /{id}/remove
  controller: App\Controller\Web\Admin\SpaceAdminController::remove
  methods: ['GET']

create:
  path: /adicionar
  controller: App\Controller\Web\Admin\SpaceAdminController::create
  methods: ['GET', 'POST']

timeline:
  path: /{id}/timeline
  controller: App\Controller\Web\Admin\SpaceAdminController::timeline
  methods: ['GET']
